services:
  - type: web
    name: listen-music
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeployTrigger: commit
    envVars:
      - key: NODE_VERSION
        value: 24.14.1
